config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :payments
  resources :payment_options
  resources :payment_descriptions
  resources :payments
  get 'dashboard/index'

  devise_for :users

  scope "/admin" do
    resources :users
  end

  resources :contracts
  resources :dashboard
  resources :tasks
  resources :properties
  resources :userdetails

  root 'dashboard#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||=User.new

    if user.role? "admin"
        can :manage , :all
    elsif user.role? "owner"
        can :manage, Property
        can :manage, Task
        can :manage, User, Contract
        can :read, :dashboard
        can :manage, Userdetail
        can :manage, Payment
    elsif user.role? "tenant"
        can :read, Property
        can :manage, Task
        can :manage, Userdetail
        can :read, :dashboard

        can :read, :contracts

        can :manage, Userdetail
        can :manage, Payment
    end

        

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :state
end

app/models/contract.rb
class Contract < ActiveRecord::Base
	mount_uploader :document, DocumentUploader

	belongs_to :user 
	belongs_to :tenant, class_name: 'User'
	belongs_to :property
	has_many :payments

end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :states
end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :owner, class_name: 'User'
	belongs_to :tenant, class_name: 'User'
	belongs_to :payment_description
	belongs_to :payment_option
	belongs_to :contract
end

app/models/payment_option.rb
class PaymentOption < ActiveRecord::Base
	has_many :payments
end

app/models/permission.rb
class Permission < ActiveRecord::Base

	belongs_to :role
	belongs_to :user
	
end

app/models/property.rb
class Property < ActiveRecord::Base

	mount_uploaders :property_documents, PropertyDocumentsUploader
	mount_uploaders :property_pictures, PropertyPicturesUploader
	belongs_to :userdetail
	belongs_to :owner, class_name: 'User'
	has_many :tasks
	has_many :contracts

	validates_presence_of :name,:property_type,:built_up_area,:owner_id,:is_available,:property_reserve,:description,:country_id,:state_id,:city_id,:address,:water_bill_details,:electricity_bill_details
	
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :permissions
	has_many :users, through: :permissions
end

app/models/state.rb
class State < ActiveRecord::Base
	belongs_to :country
	has_many :cities

	validates_presence_of :name
end

app/models/task.rb
class Task < ActiveRecord::Base
	
	belongs_to :task_type
	belongs_to :task_category
	belongs_to :userdetail
	belongs_to :property

	#validates_presence_of :title,:description,:task_type,:task_category,:property_id,:user_id,:due_date,:status,:priority
	#validate :check_due_date
	#validate :check_status

	private

	def check_due_date
		if self.due_date <= Date.today
			errors.add(:due_date, "Should be greater than today")
		end
	end

	def check_status
		if !(self.status =="New")
			errors.add(:status, "Should be new")
		end
	end
end

app/models/task_category.rb
class TaskCategory < ActiveRecord::Base
	has_many :tasks
end

app/models/task_type.rb
class TaskType < ActiveRecord::Base
	has_many :tasks
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :permissions
	has_many :roles, through: :permissions

	has_one :userdetail
	has_many :tasks

  has_many :properties, foreign_key: 'owner_id' 
  has_many :contracts , foreign_key: 'tenant_id'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         def role?(role)
         	self.roles.pluck(:name).include? role
         end
end

app/models/userdetail.rb
class Userdetail < ActiveRecord::Base
	
	mount_uploader :profile_picture, PropertyPicturesUploader
	mount_uploader :id_proof, IdProofUploader
	has_many :properties
	belongs_to :user
	validates_presence_of :name, :mobile, :user_id, :pan_no
	validates_numericality_of :mobile
	#validates_length_of :mobile,is: :10
	validates_uniqueness_of :pan_no 

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
	before_action :authenticate_user!
	load_and_authorize_resource

	def index
		@properties = Property.where('owner_id = ?',current_user.id) 
	end

	def show
		@property = Property.find(params[:id])
	end

	def new
		@property = Property.new
	end

	def create
		@property = Property.new(property_params)
		 if @property.save
		 	redirect_to properties_path, notice: "Property Successfully Added"
		 else
		 	render action: "new"
		 end
	end

	def edit
		@property = Property.find(params[:id])
	end

	def update
		@property = Property.find(params[:id])
		if @property.update_attributes(property_params)
			redirect_to properties_path
		else
			render action: "edit"
		end
	end

	def destroy
		@property = Property.find(params[:id])
		@property.delete
		redirect_to properties_path
	end
	


private
	def property_params
		params[:property].permit(:name,:property_type,:built_up_area,:owner_id,:is_available,:property_reserve,:description,:country_id,:state_id,:city_id,:address,:water_bill_details,:electricity_bill_details, {documents: []},{pictures: []})
	end

end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/properties/_form.html.erb
<%= form_for @property do |f|%>

	<div class="form-group">
	<%=f.label :name%><br>
	<%=f.text_field :name,class:"form-control"%><br>
	</div>

	
	<%=f.label :property_type%><br>
	<%=f.radio_button :property_type, "residential"%>  Residential <br>
	<%=f.radio_button :property_type, "commercial"%>  Commercial  <br>
	

	
	<%=f.hidden_field :owner_id, value: current_user.id,class:"form-control"%><br>

	<div class="form-group">
	<%=f.label :built_up_area%><br>
	<%=f.text_field :built_up_area,class:"form-control"%><br>
	</div>

	<div class="form-group">
	<%=f.label :is_available%><br>
	<%=f.radio_button :is_available, "true"%> Yes </t>
	<%=f.radio_button :is_available, "false"%> No <br>
	</div>

	<div class="form-group">	
	<%=f.label :property_reserve%><br>
	<%=f.number_field :property_reserve,class:"form-control"%><br>
	</div>

	<div class="form-group">
	<%=f.label :description%><br>
	<%=f.text_area :description,class:"form-control"%><br>
	</div>

	<div class="form-group">
	<%=f.label :country_id%>
	<%=f.collection_select :country_id, Country.all, :id, :name,{prompt:"Select Country"},{class:"form-control"} %><br>
	</div>

	<div class="form-group">
	<%=f.label :state_id%>
	<%=f.collection_select :state_id, State.all, :id, :name,{prompt:"Select State"},{class:"form-control"} %><br>
	</div>

	<div class="form-group">
	<%=f.label :city_id%>
	<%=f.collection_select :city_id, City.all, :id, :name ,{prompt:"Select City"} ,{class:"form-control"}%><br>
	</div>

	<div class="form-group">
	<%=f.label :address%><br>
	<%=f.text_area :address,class:"form-control"%><br>
	</div>

	<div class="form-group">
	<%=f.label :water_bill_details%><br>
	<%=f.text_field :water_bill_details,class:"form-control"%><br>
	</div>

	<div class="form-group">
	<%=f.label :electricity_bill_details%><br>
	<%=f.text_field :electricity_bill_details,class:"form-control"%><br>
	</div>


	<%= f.submit "Add Property", class:"btn btn-success"%>

<%end%>	

app/views/properties/edit.html.erb
<h2>Edit <%=@property.name%> Property</h2>

<%= form_for @property do |f|%>

	<%=f.label :name%><br>
	<%=f.text_field :name%><br>

	<%=f.label :property_type%><br>
	<%=f.radio_button :property_type, "residential"%>  Residential </t>
	<%=f.radio_button :property_type, "commercial"%>  Commercial  <br>

	<%=f.label :property_type%><br>
	<%=f.select :property_type, ["residential","commercial"], prompt:"Select Property Type"%>

	<%=f.hidden_field :owner_id, value: current_user.id%><br>

	<%=f.label :built_up_area%><br>
	<%=f.text_field :built_up_area%><br>

	<%=f.label :is_available%><br>
	<%=f.radio_button :is_available, "true"%> Yes </t>
	<%=f.radio_button :is_available, "false"%> No <br>
	
	<%=f.label :property_reserve%><br>
	<%=f.number_field :property_reserve%><br>

	<%=f.label :description%><br>
	<%=f.text_area :description%><br>

	<%=f.collection_select :country_id, Country.all, :id, :name %><br>

	<%=f.collection_select :state_id, State.all, :id, :name %><br>

	<%=f.collection_select :city_id, City.all, :id, :name %><br>

	<%=f.label :address%><br>
	<%=f.text_area :address%><br>

	<%=f.label :water_bill_details%><br>
	<%=f.text_field :water_bill_details%><br>

	<%=f.label :electricity_bill_details%><br>
	<%=f.text_field :electricity_bill_details%><br>

	<%=f.label :property_documents%><br>
	<%=f.file_field :property_documents , multiple: true %><br>

	<%=f.label :property_pictures%><br>
	<%=f.file_field :property_pictures , multiple: true %><br>

	<%= f.submit "Add Property"%>

<%end%>	

app/views/properties/index.html.erb
<div class="row">
<div class="page-header">
<h2>Properties
<div class="pull-right">
<%= link_to 'Add New Property', new_property_path, class: "btn btn-primary" %>
</div> <!-- button ends -->
</h2>
</div><!-- pageheader ends -->
</div> <!-- row ends -->
<hr>

<div class="row">
<%if !@properties.nil?%>
<table class="table table-bordered table-hover" id="propertiesTable">
	<thead>
		<tr>
			<th>Sl No</th>
			<th>Property Name</th>
			<th>Built Up Area</th>
			<th>Is Available?</th>
			<th>Address </th>
			<th>View Details </th>
			<th>Edit Details </th>
			<th>Remove Property </th>
		</tr>
	</thead>
	<tbody>
		
			<% @properties.each_with_index do |property,index|%>
		<tr>
			<td><%=index + 1%></td>
			<td><%=property.name%></td>
			<td><%=property.built_up_area%></td>
			<td><%=property.is_available%></td>
			<td><%=property.address%></td>
			<td><%=link_to property_path(property.id),class:"btn btn-info" do%>Show
				<span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>
				<%end%>
			</td>
			<td><%=link_to edit_property_path(property.id),class:"btn btn-warning" do%>Edit
				<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
				<%end%>
			</td>
			<td><%=link_to property_path(property.id), method: :delete, data: {confirm: "Are you sure ???"},class: "btn btn-danger" do%> Delete
				<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
			<%end%>
			</td>
		</tr>
		<%end%>
		
	</tbody>
</table>
</div>
</div> <!-- table row ends -->
<%end%>

app/views/properties/new.html.erb
<div class="row">
	<div class="page-header">
		<h2>Add New Property</h2>
	</div>
	
	<div class="col-md-8">

		<%=render 'form'%>

	</div>	

</div> <!-- row ends -->

app/views/properties/show.html.erb
<h2><%=@property.name %></h2>

<ul>
	<li><b>Name: </b><%=@property.name%></li><br>
	<li><b>Property Type: </b><%=@property.property_type%></li><br>
	<li><b>Built Up Area: </b><%=@property.built_up_area%></li><br>
	<li><b>Owner Name: </b><%#@property.userdetail.name%></li><br>
	<li><b>Is Availabe?: </b><%=@property.is_available%></li><br>
	<li><b>Property Reserve: </b><%=@property.property_reserve%></li><br>
	<li><b>Description: </b><%=@property.description%></li><br>
	<li><b>Address: </b><%=@property.address%></li><br>
	<li><b>Water Bill Details: </b><%=@property.water_bill_details%></li><br>
	<li><b>Electricity Bill Details: </b><%=@property.electricity_bill_details%></li><br>
</ul>