config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :payments
  resources :payment_options
  resources :payment_descriptions
  resources :payments
  get 'dashboard/index'

  devise_for :users

  scope "/admin" do
    resources :users
  end

  resources :contracts
  resources :dashboard
  resources :tasks
  resources :properties
  resources :userdetails

  root 'dashboard#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||=User.new

    if user.role? "admin"
        can :manage , :all
    elsif user.role? "owner"
        can :manage, Property
        can :manage, Task
        can :manage, User, Contract
        can :read, :dashboard
        can :manage, Userdetail
        can :manage, Payment
    elsif user.role? "tenant"
        can :read, Property
        can :manage, Task
        can :manage, Userdetail
        can :read, :dashboard

        can :read, :contracts

        can :manage, Userdetail
        can :manage, Payment
    end

        

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :state
end

app/models/contract.rb
class Contract < ActiveRecord::Base
	mount_uploader :document, DocumentUploader

	belongs_to :user 
	belongs_to :tenant, class_name: 'User'
	belongs_to :property
	has_many :payments

end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :states
end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :owner, class_name: 'User'
	belongs_to :tenant, class_name: 'User'
	belongs_to :payment_description
	belongs_to :payment_option
	belongs_to :contract
end

app/models/payment_description.rb
class PaymentDescription < ActiveRecord::Base
	has_many :payments

	def display_info
		self.payment_type + "--- "+" " + self.payment_description 
	end
end

app/models/payment_option.rb
class PaymentOption < ActiveRecord::Base
	has_many :payments
end

app/models/permission.rb
class Permission < ActiveRecord::Base

	belongs_to :role
	belongs_to :user
	
end

app/models/property.rb
class Property < ActiveRecord::Base

	mount_uploaders :property_documents, PropertyDocumentsUploader
	mount_uploaders :property_pictures, PropertyPicturesUploader
	belongs_to :userdetail
	belongs_to :owner, class_name: 'User'
	has_many :tasks
	has_many :contracts

	validates_presence_of :name,:property_type,:built_up_area,:owner_id,:is_available,:property_reserve,:description,:country_id,:state_id,:city_id,:address,:water_bill_details,:electricity_bill_details
	
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :permissions
	has_many :users, through: :permissions
end

app/models/state.rb
class State < ActiveRecord::Base
	belongs_to :country
	has_many :cities

	validates_presence_of :name
end

app/models/task.rb
class Task < ActiveRecord::Base
	
	belongs_to :task_type
	belongs_to :task_category
	belongs_to :userdetail
	belongs_to :property

	#validates_presence_of :title,:description,:task_type,:task_category,:property_id,:user_id,:due_date,:status,:priority
	#validate :check_due_date
	#validate :check_status

	private

	def check_due_date
		if self.due_date <= Date.today
			errors.add(:due_date, "Should be greater than today")
		end
	end

	def check_status
		if !(self.status =="New")
			errors.add(:status, "Should be new")
		end
	end
end

app/models/task_category.rb
class TaskCategory < ActiveRecord::Base
	has_many :tasks
end

app/models/task_type.rb
class TaskType < ActiveRecord::Base
	has_many :tasks
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :permissions
	has_many :roles, through: :permissions

	has_one :userdetail
	has_many :tasks

  has_many :properties, foreign_key: 'owner_id' 
  has_many :contracts , foreign_key: 'tenant_id'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         def role?(role)
         	self.roles.pluck(:name).include? role
         end
end

app/models/userdetail.rb
class Userdetail < ActiveRecord::Base
	
	mount_uploader :profile_picture, PropertyPicturesUploader
	mount_uploader :id_proof, IdProofUploader
	has_many :properties
	belongs_to :user
	validates_presence_of :name, :mobile, :user_id, :pan_no
	validates_numericality_of :mobile
	#validates_length_of :mobile,is: :10
	validates_uniqueness_of :pan_no 

end

app/controllers/payment_descriptions_controller.rb
class PaymentDescriptionsController < ApplicationController
  before_action :set_payment_description, only: [:show, :edit, :update, :destroy]

  # GET /payment_descriptions
  # GET /payment_descriptions.json
  def index
    @payment_descriptions = PaymentDescription.all
  end

  # GET /payment_descriptions/1
  # GET /payment_descriptions/1.json
  def show
  end

  # GET /payment_descriptions/new
  def new
    @payment_description = PaymentDescription.new
  end

  # GET /payment_descriptions/1/edit
  def edit
  end

  # POST /payment_descriptions
  # POST /payment_descriptions.json
  def create
    @payment_description = PaymentDescription.new(payment_description_params)

    respond_to do |format|
      if @payment_description.save
        format.html { redirect_to @payment_description, notice: 'Payment description was successfully created.' }
        format.json { render :show, status: :created, location: @payment_description }
      else
        format.html { render :new }
        format.json { render json: @payment_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_descriptions/1
  # PATCH/PUT /payment_descriptions/1.json
  def update
    respond_to do |format|
      if @payment_description.update(payment_description_params)
        format.html { redirect_to @payment_description, notice: 'Payment description was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_description }
      else
        format.html { render :edit }
        format.json { render json: @payment_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_descriptions/1
  # DELETE /payment_descriptions/1.json
  def destroy
    @payment_description.destroy
    respond_to do |format|
      format.html { redirect_to payment_descriptions_url, notice: 'Payment description was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_description
      @payment_description = PaymentDescription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_description_params
      params.require(:payment_description).permit(:payment_type, :payment_description)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payment_descriptions_helper.rb
module PaymentDescriptionsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/payment_descriptions/_form.html.erb
<%= form_for(@payment_description) do |f| %>
  <% if @payment_description.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_description.errors.count, "error") %> prohibited this payment_description from being saved:</h2>

      <ul>
      <% @payment_description.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :payment_type %><br>
    <%= f.text_field :payment_type %>
  </div>
  <div class="field">
    <%= f.label :payment_description %><br>
    <%= f.text_field :payment_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_descriptions/edit.html.erb
<h1>Editing Payment Description</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_description %> |
<%= link_to 'Back', payment_descriptions_path %>

app/views/payment_descriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Payment Descriptions</h1>

<table>
  <thead>
    <tr>
      <th>Payment type</th>
      <th>Payment description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_descriptions.each do |payment_description| %>
      <tr>
        <td><%= payment_description.payment_type %></td>
        <td><%= payment_description.payment_description %></td>
        <td><%= link_to 'Show', payment_description %></td>
        <td><%= link_to 'Edit', edit_payment_description_path(payment_description) %></td>
        <td><%= link_to 'Destroy', payment_description, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment description', new_payment_description_path %>

app/views/payment_descriptions/new.html.erb
<h1>New Payment Description</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_descriptions_path %>

app/views/payment_descriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Payment type:</strong>
  <%= @payment_description.payment_type %>
</p>

<p>
  <strong>Payment description:</strong>
  <%= @payment_description.payment_description %>
</p>

<%= link_to 'Edit', edit_payment_description_path(@payment_description) %> |
<%= link_to 'Back', payment_descriptions_path %>